-- AlterTable
ALTER TABLE "country" ALTER COLUMN "created" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "likes" ALTER COLUMN "created" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "post" ALTER COLUMN "file" SET DEFAULT NULL,
ALTER COLUMN "created" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "video_id" SET DEFAULT NULL;

-- AlterTable
ALTER TABLE "user" ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "created" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "video" ALTER COLUMN "v1080p" SET DEFAULT NULL,
ALTER COLUMN "v720p" SET DEFAULT NULL,
ALTER COLUMN "v480p" SET DEFAULT NULL,
ALTER COLUMN "v144p" SET DEFAULT NULL;
